#These users will be allowed to grant OP or full perms *
Anti-Hacks-Protection: false
SafeUsers:
- brunyman
- henkekalmar
RestrictedCmdSafeUsers:
- lp
- luckperms
- perms
- op
- permissions
- perm

#Chat messages with color codes suport.
ChatMessage:
    CommandRestricted: '&4[HackYou OS] &cYou are not authorized to use this command! If this is an error contact us, else go hack BACON'
